version: "3"

tasks:
  lint:
    cmds:
      - golangci-lint run ./...
      - gofumpt -l .
      - go mod tidy -diff

  test:
    cmds:
      - go test -race ./...

  vuln:
    cmds:
      - go run golang.org/x/vuln/cmd/govulncheck@v1.8.0 ./...

  ci:
    deps: [lint, test, vuln]
